### ISSUE TITLE
Entire rule being overwritten

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/crbuilder#13]
id: b73b3597-ee31-4629-aaa1-30a8d08a04f4
original ruleid: CG0437
new ruleid: CG0415

The original rule has yaml that is likely not able to be parsed. If a rule's yaml cannot be parsed, it should not be updated.
For some reason, the rule is being completely replaced by a new rule, CG0415.
This is probably because the CG0415 content is still in memory from the previous rule.

I would expect the original unparsable rule to be unchanged and a new rule CG0437 to be added.

**Comment by htu** [comment]
OK. This rule has ":" in the text which causes the issue. I will create a special case for this.

**Comment by htu** [comment]
How do you relate CG0437 with CG0415? I do not see what you described, i.e., CG0437 has CG0415 contents. BTW, CG0415 has two documents.

**Comment by gerrycampion** [comment]
You shouldn't need a special case. In general, if a rule content cannot be converted to json, it should not be updated.
You can see the relationship by looking up the original (in prod) and updated rule (in dev) using the id b73b3597-ee31-4629-aaa1-30a8d08a04f4
There is 1 CG0415 input document and 2 CG0415 output documents. This is because the input document is being updated (correctly) AND an additional CG0437 is being replaced (incorrectly) by CG0415 from contents of the previous iteration of the loop.

**Comment by htu** [comment]
Since Rule CG0437 has a problem, it did not get copied over and a new document is generated for it. So it is not overwritten since the new doc has a new GUID. 
`YAML
Description: Verify that --SOCCD matches MedDRA primary system organ class code
Sensitivity: Value
Severity: Error                     :
Scopes:
  Standards:
    - Name: SDTMIG
      Version: "3.4"
  Classes:
    # {Source Class: EVT}
    Include:
      - Events
  Domains:
    # {Source Domains: AE, MH, CE}
    Include:
      - AE
      - MH
      - CE
#need operator/function to cross check and verify dataset --SOCCD against MedDRA SOCCD (any dictionary #lookup) ,drafting using the logic of the cross dataset check for now
`

**Comment by htu** [comment]
I am closing this one since this issue is due to the documents did not get copied over.
